version: "3.9"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQLDB_USER=$MYSQL_USER
      - MYSQLDB_PASSWORD=$MYSQL_PASSWORD
      - MYSQLDB_DATABASE=$MYSQL_DATABASE
      - MYSQLDB_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: meditrust-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
